/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedRoutinesRouteImport } from './routes/_authenticated/routines'
import { Route as AuthenticatedWinsRouteImport } from './routes/_authenticated/wins'
import { Route as AuthenticatedGoalsIndexRouteImport } from './routes/_authenticated/goals.index'
import { Route as AuthenticatedGoalsGoalIdRouteImport } from './routes/_authenticated/goals.$goalId'
import { Route as AuthenticatedGoalsNewRouteImport } from './routes/_authenticated/goals.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutinesRoute = AuthenticatedRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWinsRoute = AuthenticatedWinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsIndexRoute = AuthenticatedGoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGoalsRoute,
} as any)
const AuthenticatedGoalsGoalIdRoute =
  AuthenticatedGoalsGoalIdRouteImport.update({
    id: '/$goalId',
    path: '/$goalId',
    getParentRoute: () => AuthenticatedGoalsRoute,
  } as any)
const AuthenticatedGoalsNewRoute = AuthenticatedGoalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedGoalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/habits': typeof AuthenticatedHabitsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/routines': typeof AuthenticatedRoutinesRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/goals/new': typeof AuthenticatedGoalsNewRoute
  '/goals/': typeof AuthenticatedGoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/routines': typeof AuthenticatedRoutinesRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/goals/new': typeof AuthenticatedGoalsNewRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/routines': typeof AuthenticatedRoutinesRoute
  '/_authenticated/wins': typeof AuthenticatedWinsRoute
  '/_authenticated/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/_authenticated/goals/new': typeof AuthenticatedGoalsNewRoute
  '/_authenticated/goals/': typeof AuthenticatedGoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/goals'
    | '/habits'
    | '/overview'
    | '/routines'
    | '/wins'
    | '/goals/$goalId'
    | '/goals/new'
    | '/goals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/habits'
    | '/overview'
    | '/routines'
    | '/wins'
    | '/goals/$goalId'
    | '/goals/new'
    | '/goals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/overview'
    | '/_authenticated/routines'
    | '/_authenticated/wins'
    | '/_authenticated/goals/$goalId'
    | '/_authenticated/goals/new'
    | '/_authenticated/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routines': {
      id: '/_authenticated/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AuthenticatedRoutinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wins': {
      id: '/_authenticated/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof AuthenticatedWinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/': {
      id: '/_authenticated/goals/'
      path: '/'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthenticatedGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/goals/$goalId': {
      id: '/_authenticated/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthenticatedGoalsGoalIdRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/goals/new': {
      id: '/_authenticated/goals/new'
      path: '/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof AuthenticatedGoalsNewRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
  }
}

interface AuthenticatedGoalsRouteChildren {
  AuthenticatedGoalsGoalIdRoute: typeof AuthenticatedGoalsGoalIdRoute
  AuthenticatedGoalsNewRoute: typeof AuthenticatedGoalsNewRoute
  AuthenticatedGoalsIndexRoute: typeof AuthenticatedGoalsIndexRoute
}

const AuthenticatedGoalsRouteChildren: AuthenticatedGoalsRouteChildren = {
  AuthenticatedGoalsGoalIdRoute: AuthenticatedGoalsGoalIdRoute,
  AuthenticatedGoalsNewRoute: AuthenticatedGoalsNewRoute,
  AuthenticatedGoalsIndexRoute: AuthenticatedGoalsIndexRoute,
}

const AuthenticatedGoalsRouteWithChildren =
  AuthenticatedGoalsRoute._addFileChildren(AuthenticatedGoalsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRouteWithChildren
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedRoutinesRoute: typeof AuthenticatedRoutinesRoute
  AuthenticatedWinsRoute: typeof AuthenticatedWinsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGoalsRoute: AuthenticatedGoalsRouteWithChildren,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedRoutinesRoute: AuthenticatedRoutinesRoute,
  AuthenticatedWinsRoute: AuthenticatedWinsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
