/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBraindumpRouteImport } from './routes/_authenticated/braindump'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedRoutinesRouteImport } from './routes/_authenticated/routines'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedWinsRouteImport } from './routes/_authenticated/wins'
import { Route as AuthenticatedGoalsIndexRouteImport } from './routes/_authenticated/goals.index'
import { Route as AuthenticatedGoalsGoalIdRouteImport } from './routes/_authenticated/goals.$goalId'
import { Route as AuthenticatedGoalsNewRouteImport } from './routes/_authenticated/goals.new'
import { Route as AuthenticatedRoutinesIndexRouteImport } from './routes/_authenticated/routines.index'
import { Route as AuthenticatedRoutinesRoutineIdRouteImport } from './routes/_authenticated/routines.$routineId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBraindumpRoute = AuthenticatedBraindumpRouteImport.update({
  id: '/braindump',
  path: '/braindump',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutinesRoute = AuthenticatedRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWinsRoute = AuthenticatedWinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsIndexRoute = AuthenticatedGoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGoalsRoute,
} as any)
const AuthenticatedGoalsGoalIdRoute =
  AuthenticatedGoalsGoalIdRouteImport.update({
    id: '/$goalId',
    path: '/$goalId',
    getParentRoute: () => AuthenticatedGoalsRoute,
  } as any)
const AuthenticatedGoalsNewRoute = AuthenticatedGoalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedGoalsRoute,
} as any)
const AuthenticatedRoutinesIndexRoute =
  AuthenticatedRoutinesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoutinesRoute,
  } as any)
const AuthenticatedRoutinesRoutineIdRoute =
  AuthenticatedRoutinesRoutineIdRouteImport.update({
    id: '/$routineId',
    path: '/$routineId',
    getParentRoute: () => AuthenticatedRoutinesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/braindump': typeof AuthenticatedBraindumpRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/habits': typeof AuthenticatedHabitsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/routines': typeof AuthenticatedRoutinesRouteWithChildren
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/goals/new': typeof AuthenticatedGoalsNewRoute
  '/routines/$routineId': typeof AuthenticatedRoutinesRoutineIdRoute
  '/goals/': typeof AuthenticatedGoalsIndexRoute
  '/routines/': typeof AuthenticatedRoutinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/braindump': typeof AuthenticatedBraindumpRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/goals/new': typeof AuthenticatedGoalsNewRoute
  '/routines/$routineId': typeof AuthenticatedRoutinesRoutineIdRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
  '/routines': typeof AuthenticatedRoutinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/braindump': typeof AuthenticatedBraindumpRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRouteWithChildren
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/routines': typeof AuthenticatedRoutinesRouteWithChildren
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_authenticated/wins': typeof AuthenticatedWinsRoute
  '/_authenticated/goals/$goalId': typeof AuthenticatedGoalsGoalIdRoute
  '/_authenticated/goals/new': typeof AuthenticatedGoalsNewRoute
  '/_authenticated/routines/$routineId': typeof AuthenticatedRoutinesRoutineIdRoute
  '/_authenticated/goals/': typeof AuthenticatedGoalsIndexRoute
  '/_authenticated/routines/': typeof AuthenticatedRoutinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/braindump'
    | '/finance'
    | '/gallery'
    | '/goals'
    | '/habits'
    | '/overview'
    | '/routines'
    | '/welcome'
    | '/wins'
    | '/goals/$goalId'
    | '/goals/new'
    | '/routines/$routineId'
    | '/goals/'
    | '/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/braindump'
    | '/finance'
    | '/gallery'
    | '/habits'
    | '/overview'
    | '/welcome'
    | '/wins'
    | '/goals/$goalId'
    | '/goals/new'
    | '/routines/$routineId'
    | '/goals'
    | '/routines'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/braindump'
    | '/_authenticated/finance'
    | '/_authenticated/gallery'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/overview'
    | '/_authenticated/routines'
    | '/_authenticated/welcome'
    | '/_authenticated/wins'
    | '/_authenticated/goals/$goalId'
    | '/_authenticated/goals/new'
    | '/_authenticated/routines/$routineId'
    | '/_authenticated/goals/'
    | '/_authenticated/routines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/braindump': {
      id: '/_authenticated/braindump'
      path: '/braindump'
      fullPath: '/braindump'
      preLoaderRoute: typeof AuthenticatedBraindumpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routines': {
      id: '/_authenticated/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AuthenticatedRoutinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wins': {
      id: '/_authenticated/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof AuthenticatedWinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/': {
      id: '/_authenticated/goals/'
      path: '/'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthenticatedGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/goals/$goalId': {
      id: '/_authenticated/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthenticatedGoalsGoalIdRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/goals/new': {
      id: '/_authenticated/goals/new'
      path: '/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof AuthenticatedGoalsNewRouteImport
      parentRoute: typeof AuthenticatedGoalsRoute
    }
    '/_authenticated/routines/': {
      id: '/_authenticated/routines/'
      path: '/'
      fullPath: '/routines/'
      preLoaderRoute: typeof AuthenticatedRoutinesIndexRouteImport
      parentRoute: typeof AuthenticatedRoutinesRoute
    }
    '/_authenticated/routines/$routineId': {
      id: '/_authenticated/routines/$routineId'
      path: '/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof AuthenticatedRoutinesRoutineIdRouteImport
      parentRoute: typeof AuthenticatedRoutinesRoute
    }
  }
}

interface AuthenticatedGoalsRouteChildren {
  AuthenticatedGoalsGoalIdRoute: typeof AuthenticatedGoalsGoalIdRoute
  AuthenticatedGoalsNewRoute: typeof AuthenticatedGoalsNewRoute
  AuthenticatedGoalsIndexRoute: typeof AuthenticatedGoalsIndexRoute
}

const AuthenticatedGoalsRouteChildren: AuthenticatedGoalsRouteChildren = {
  AuthenticatedGoalsGoalIdRoute: AuthenticatedGoalsGoalIdRoute,
  AuthenticatedGoalsNewRoute: AuthenticatedGoalsNewRoute,
  AuthenticatedGoalsIndexRoute: AuthenticatedGoalsIndexRoute,
}

const AuthenticatedGoalsRouteWithChildren =
  AuthenticatedGoalsRoute._addFileChildren(AuthenticatedGoalsRouteChildren)

interface AuthenticatedRoutinesRouteChildren {
  AuthenticatedRoutinesRoutineIdRoute: typeof AuthenticatedRoutinesRoutineIdRoute
  AuthenticatedRoutinesIndexRoute: typeof AuthenticatedRoutinesIndexRoute
}

const AuthenticatedRoutinesRouteChildren: AuthenticatedRoutinesRouteChildren = {
  AuthenticatedRoutinesRoutineIdRoute: AuthenticatedRoutinesRoutineIdRoute,
  AuthenticatedRoutinesIndexRoute: AuthenticatedRoutinesIndexRoute,
}

const AuthenticatedRoutinesRouteWithChildren =
  AuthenticatedRoutinesRoute._addFileChildren(
    AuthenticatedRoutinesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBraindumpRoute: typeof AuthenticatedBraindumpRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRouteWithChildren
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedRoutinesRoute: typeof AuthenticatedRoutinesRouteWithChildren
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedWinsRoute: typeof AuthenticatedWinsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBraindumpRoute: AuthenticatedBraindumpRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRouteWithChildren,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedRoutinesRoute: AuthenticatedRoutinesRouteWithChildren,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedWinsRoute: AuthenticatedWinsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
